name: Java CI с Gradle

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Настройка JDK 11
        uses: actions/setup-java@v2
        with:
          java-version: '11'  # Версию JDK ставим согласно требованиям проекта
          distribution: 'adopt'  # Используем OpenJDK от AdoptOpenJDK

      - name: Предоставить разрешение на выполнение для gradlew
        run: chmod +x gradlew

      - name: Запустить SUT (SUT — система под тестированием)
        run: java -jar ./artifacts/app-order.jar &

      - name: Собрать проект с помощью Gradle
        run: |
          # Для проектов на базе Selenide добавляем аргумент "-Dselenide.headless=true",
          # чтобы браузер работал в headless режиме (без графического интерфейса).
          # Параметр "--info" нужен для вывода подробной информации о ходе сборки.
          ./gradlew test --info -Dselenide.headless=true